# Generated by Django 2.1.1 on 2018-09-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('prerequisite', models.CharField(max_length=25)),
                ('yearsofstudy', models.CharField(max_length=25)),
                ('faculty', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=25)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('cities', models.ManyToManyField(to='api.City')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=8)),
                ('cities', models.ManyToManyField(to='api.City')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='fields',
            field=models.ManyToManyField(to='api.Field'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.University'),
        ),
        migrations.AddField(
            model_name='district',
            name='neighborhoods',
            field=models.ManyToManyField(to='api.Neighborhood'),
        ),
        migrations.AddField(
            model_name='course',
            name='fields',
            field=models.ManyToManyField(to='api.Field'),
        ),
        migrations.AddField(
            model_name='course',
            name='professions',
            field=models.ManyToManyField(to='api.Profession'),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.University'),
        ),
        migrations.AddField(
            model_name='city',
            name='districts',
            field=models.ManyToManyField(to='api.District'),
        ),
    ]
